### ISSUE TITLE
try/catch nso interceptor

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/vraptor-dash#12]
os interceptors tinham que garantir que NAO IMPORTA o que eles devem funcionar

**Comment by josedonizetti** [comment]
those try/catch should do anything more than logging?

**Comment by guilhermesilveira** [comment]
just log so we know there is a problem with the plugin but the program works
as expected

Guilherme Silveira
On Aug 15, 2011 11:03 AM, "josedonizetti" <
reply@reply.github.com>
wrote:
