### ISSUE TITLE
queries with < will cause panic on the index file

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/vraptor-dash#13]
query hql should be html escaped prior to printing

**Comment by josedonizetti** [comment]
when is this problem occuring? I've tried a few queries with < and > and it has worked.

**Comment by guilhermesilveira** [comment]
twhen it appears on the list of saved queries there is no problrm?

Guilherme Silveira
On Aug 15, 2011 10:49 AM, "josedonizetti" <
reply@reply.github.com>
wrote:

**Comment by josedonizetti** [comment]
gui I was facing no problem, even when saving a query but it could be a matter of browser so I've escaped it anyway.

**Comment by guilhermesilveira** [comment]
great!

Guilherme Silveira
Caelum | Ensino e Inovação
http://www.caelum.com.br/

On Mon, Aug 15, 2011 at 11:34 AM, josedonizetti
reply@reply.github.com
wrote:
