### ISSUE TITLE
show all routes (fix it)

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/vraptor-dash#26]

**Comment by josedonizetti** [comment]
what you mean by fixing it?

**Comment by guilhermesilveira** [comment]
there is already a controller for.that. you only need to make it work.
"only" hehe

Guilherme Silveira
On Aug 11, 2011 9:10 PM, "josedonizetti" <
reply@reply.github.com>
wrote:

**Comment by steppat** [comment]
Is there any to discover the controller method form a given route? I have a list of route objects and would like to know the associated controller method.

**Comment by guilhermesilveira** [comment]
Yes

Cast it to fixedpatternrule and you can get it

Regexbasedones dont provide this info

Guilherme Silveira
On Aug 25, 2011 1:16 PM, "steppat" <
reply@reply.github.com>
wrote:

**Comment by steppat** [comment]
I should have asked: Anyway to discover the controller method without depending on the implementation? also, shouldn't this information be provided by the Route interface?

**Comment by guilhermesilveira** [comment]
thats the point. There is no suh a tjing as a one to one mapping of a route
to a method.
but a fixedroute has.

You can define a getRoutes method... But it will require a for to implemebt
for the regex based one

Guilherme Silveira
On Aug 25, 2011 3:52 PM, "steppat" <
reply@reply.github.com>
wrote:
