### ISSUE TITLE
content-type is not set to text/html :(. freemarker should automatically do it?

### ISSUE THREAD

**Issue by guilhermesilveira** [caelum/vraptor-dash#30]

**Comment by josedonizetti** [comment]
As every method was setting the content-type to text/html at your last line, i've extracted it to a vraptor's interceptor so that every request will have your response content-type seted. Any issues can happen from that? Opnions?

**Comment by guilhermesilveira** [comment]
its actually still not.working in gnarus. ill leave it to.them so they can
test and fix it...

Guilherme Silveira
On Aug 21, 2011 10:38 PM, "josedonizetti" <
reply@reply.github.com>
wrote:

**Comment by josedonizetti** [comment]
Ok. It's just a matter of disabling the filter through the accepts, and then removing it from the code base if not necessary.
